// ===== FIREBASE PROJECT CONFIGURATION =====
// Replace these with your Firebase project credentials
export const firebaseConfig = {
  apiKey: "your_api_key_here",
  authDomain: "your_project.firebaseapp.com",
  projectId: "your_project_id",
  storageBucket: "your_project.appspot.com",
  messagingSenderId: "your_sender_id",
  appId: "your_app_id",
}

// ===== DATABASE COLLECTIONS =====
// Modify collection names to match your Firebase database
export const collections = {
  helmets: "smart_helmets", // Main helmet data collection
  alerts: "helmet_alerts", // Alert notifications collection
  workers: "workers", // Worker information collection
  locations: "locations", // Location tracking collection
  reports: "reports", // Safety reports collection
}

// ===== DATA MODEL CONFIGURATION =====
// Define your helmet data structure - modify fields as needed
export const helmetDataModel = {
  // Required fields (must be present)
  required: ["workerName", "isActive", "batteryLevel", "location"],

  // Default values for new helmets
  defaults: {
    impactStatus: "normal",
    ledStatus: "off",
    impactCount: 0,
    workingHours: 0,
    safetyScore: 100,
    temperature: 25,
    humidity: 50,
    lastMaintenance: null,
    firmwareVersion: "1.0.0",
    isOnline: false,
  },

  // Field validation rules
  validation: {
    batteryLevel: { min: 0, max: 100 },
    impactStatus: ["normal", "warning", "critical", "emergency"],
    ledStatus: ["green", "red", "blue", "yellow", "off"],
    safetyScore: { min: 0, max: 100 },
    temperature: { min: -20, max: 60 },
    humidity: { min: 0, max: 100 },
  },
}

// Alert data model
export const alertDataModel = {
  required: ["type", "message", "helmetId"],
  defaults: {
    isRead: false,
    priority: "medium",
    resolved: false,
    autoGenerated: true,
  },
  validation: {
    type: ["impact", "battery", "offline", "temperature", "maintenance", "geofence"],
    priority: ["low", "medium", "high", "critical"],
  },
}

export const dataModels = {
  helmet: helmetDataModel,
  alert: alertDataModel,
}

// ===== CORE VARIABLES CONFIGURATION =====
export const helmetVariables = {
  // FSR402 Sensor Settings
  fsrSensor: {
    threshold: 500, // Pressure threshold (0-1023)
    sensitivity: "medium", // low, medium, high
    calibration: 0, // Calibration offset
    isActive: true, // Enable/disable FSR monitoring
  },

  // Active Period Settings
  activePeriod: {
    startTime: "08:00", // Work start time
    endTime: "17:00", // Work end time
    breakDuration: 60, // Break time in minutes
    maxWorkHours: 8, // Maximum work hours per day
    autoShutoff: true, // Auto deactivate after work hours
  },

  // Battery Settings
  battery: {
    lowThreshold: 20, // Low battery warning %
    criticalThreshold: 10, // Critical battery warning %
    chargingVoltage: 4.2, // Full charge voltage
    updateInterval: 30, // Battery check interval (seconds)
  },

  // Location Settings
  location: {
    updateInterval: 10, // GPS update interval (seconds)
    accuracy: 5, // Required GPS accuracy (meters)
    geofenceRadius: 100, // Work area radius (meters)
    enableTracking: true, // Enable/disable location tracking
  },
}

// ===== REAL-TIME UPDATE SETTINGS =====
export const realtimeSettings = {
  enableRealtime: true,
  updateFrequency: 2000, // Update every 2 seconds
  maxRetries: 3,
  autoReconnect: true,
}

// ===== DASHBOARD CONFIGURATION =====
export const dashboardConfig = {
  // Main dashboard settings
  refreshInterval: 3000, // Dashboard refresh rate
  maxAlertsDisplay: 8, // Max alerts to show
  defaultView: "dashboard", // Default tab: dashboard, map, analytics

  // Stats cards configuration - modify or add new stats
  statsCards: [
    {
      key: "activeHelmets",
      label: "Active Helmets",
      icon: "Shield",
      color: "green",
      format: "fraction", // Shows as "2/5"
    },
    {
      key: "totalImpacts",
      label: "Total Impacts",
      icon: "Zap",
      color: "yellow",
      format: "number",
    },
    {
      key: "avgBattery",
      label: "Avg Battery",
      icon: "Battery",
      color: "blue",
      format: "percentage",
    },
    {
      key: "workingHours",
      label: "Working Hours",
      icon: "Clock",
      color: "purple",
      format: "hours",
    },
    {
      key: "safetyScore",
      label: "Safety Score",
      icon: "Award",
      color: "green",
      format: "percentage",
    },
  ],

  // Alert configuration
  alertConfig: {
    enableSound: true,
    enableBrowserNotifications: true,
    criticalAlertColor: "red",
    warningAlertColor: "yellow",
    infoAlertColor: "blue",
  },
}

// ===== FIELD DISPLAY CONFIGURATION =====
// Customize how fields are displayed in the UI
export const fieldDisplayConfig = {
  helmet: {
    workerName: { label: "Worker Name", icon: "User", editable: true },
    isActive: { label: "Active Status", icon: "Power", editable: true },
    batteryLevel: { label: "Battery Level", icon: "Battery", editable: true, suffix: "%" },
    impactStatus: { label: "Impact Status", icon: "Activity", editable: true },
    ledStatus: { label: "LED Status", icon: "Lightbulb", editable: true },
    impactCount: { label: "Impact Count", icon: "Zap", editable: false },
    workingHours: { label: "Working Hours", icon: "Clock", editable: true, suffix: "h" },
    safetyScore: { label: "Safety Score", icon: "Award", editable: false, suffix: "%" },
    temperature: { label: "Temperature", icon: "Thermometer", editable: false, suffix: "°C" },
    humidity: { label: "Humidity", icon: "Droplets", editable: false, suffix: "%" },
    firmwareVersion: { label: "Firmware", icon: "Cpu", editable: false },
  },
}

// ===== LOCATION CONFIGURATION =====
export const locationConfig = {
  defaultLocation: {
    lat: -6.2088,
    lng: 106.8456,
    address: "Construction Site A, Jakarta, Indonesia",
  },
  mapSettings: {
    zoom: 15,
    enableClustering: true,
    showTrails: false,
    updateInterval: 5000,
  },
}

// ===== NOTIFICATION CONFIGURATION =====
export const notificationConfig = {
  enablePushNotifications: true,
  enableEmailAlerts: false,
  enableSMSAlerts: false,

  // Auto-alert thresholds
  thresholds: {
    lowBattery: 20, // Battery % to trigger low battery alert
    criticalBattery: 10, // Battery % to trigger critical alert
    highTemperature: 45, // Temperature to trigger heat alert
    impactThreshold: 5, // G-force threshold for impact detection
    offlineTimeout: 300000, // Milliseconds before marking as offline
  },
}

// ===== CUSTOM FEATURES TOGGLE =====
export const featureFlags = {
  enableTemperatureMonitoring: true,
  enableHumidityMonitoring: true,
  enableGeofencing: false,
  enableVoiceAlerts: false,
  enableCameraIntegration: false,
  enableMaintenanceScheduling: true,
  enableDataExport: true,
  enableUserManagement: false,
}
